CREATE  TABLE IF NOT EXISTS `USER_TEST`.`USER` (
  `ID` INT  AUTO_INCREMENT ,
  `FIRST_NAME` VARCHAR(150) NOT NULL ,
  `MIDDLE_NAME` VARCHAR(150) ,
  `LAST_NAME` VARCHAR(150) NOT NULL ,
  `OTHER_NAMES` VARCHAR(150) ,
  `GENDER` VARCHAR(6) NOT NULL,
  `DATE_OF_BIRTH` DATE ,
  `CONTACT` VARCHAR(75) ,
  `EMAIL` VARCHAR(255) ,
  PRIMARY KEY (`ID`) );
  

ALTER TABLE penguins AUTO_INCREMENT=1001;

COMMIT;